"""UUIDs for python working

Revision ID: daa4dcc0d7ca
Revises: 7d378977f2ec
Create Date: 2020-03-16 21:06:56.341007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa4dcc0d7ca'
down_revision = '7d378977f2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
