"""use uuid for id

Revision ID: bda80e67d310
Revises: edaf2fb54741
Create Date: 2020-03-16 20:50:50.951520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda80e67d310'
down_revision = 'edaf2fb54741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
