"""UUID

Revision ID: 7d378977f2ec
Revises: 47e608135db8
Create Date: 2020-03-16 21:03:57.709809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d378977f2ec'
down_revision = '47e608135db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_todos'))
    )
    op.create_index('todo_index', 'todos', ['body'], unique=False, mysql_length=255)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('todo_index', table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###
