"""Field not unique

Revision ID: c1931bf6e52a
Revises: 412d77eead11
Create Date: 2020-03-16 10:48:08.621334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1931bf6e52a'
down_revision = '412d77eead11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('todo_index', table_name='todos')
    op.create_index('todo_index', 'todos', ['body'], unique=False, mysql_length=255)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('todo_index', table_name='todos')
    op.create_index('todo_index', 'todos', ['body'], unique=True)
    # ### end Alembic commands ###
