"""id

Revision ID: 47e608135db8
Revises: 5a39f69972e0
Create Date: 2020-03-16 21:02:24.804987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e608135db8'
down_revision = '5a39f69972e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
