"""todos

Revision ID: 20b992fc0b0c
Revises: 5b007b367579
Create Date: 2020-03-15 10:14:28.589287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b992fc0b0c'
down_revision = '5b007b367579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
