"""make autoincrement

Revision ID: 033218924669
Revises: c1931bf6e52a
Create Date: 2020-03-16 11:26:17.976267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033218924669'
down_revision = 'c1931bf6e52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
