"""todos

Revision ID: fe5a2ad069c2
Revises: d2d4d74a0b1e
Create Date: 2020-03-15 10:33:24.284555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5a2ad069c2'
down_revision = 'd2d4d74a0b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_todos'))
    )
    op.create_index('todo_index', 'todos', ['body'], unique=True, mysql_length=255)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('todo_index', table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###
