"""next

Revision ID: d2d4d74a0b1e
Revises: 20b992fc0b0c
Create Date: 2020-03-15 10:26:03.712789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d4d74a0b1e'
down_revision = '20b992fc0b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
