"""make complete false and body non nullable

Revision ID: 412d77eead11
Revises: fe5a2ad069c2
Create Date: 2020-03-16 08:58:47.551473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412d77eead11'
down_revision = 'fe5a2ad069c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
