"""init

Revision ID: 5b007b367579
Revises: 5c18ae5cb446
Create Date: 2020-03-15 10:08:41.598045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b007b367579'
down_revision = '5c18ae5cb446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
