"""Working add

Revision ID: 492ec66d34fc
Revises: 033218924669
Create Date: 2020-03-16 11:49:52.743550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492ec66d34fc'
down_revision = '033218924669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
