"""use uuid for id

Revision ID: edaf2fb54741
Revises: 5e3e2ca2fea3
Create Date: 2020-03-16 20:44:55.079644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edaf2fb54741'
down_revision = '5e3e2ca2fea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
